-- =============================================================
-- 1. Create the snapshot table: organization_plan_limits
--    Stores the limits each org was given when they entered a plan.
--    Global plan_limits becomes a "template" for new assignments.
-- =============================================================
CREATE TABLE public.organization_plan_limits (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organization(id),
  plan            TEXT NOT NULL CHECK (plan = ANY (ARRAY['trial','advance','pro'])),
  feature         TEXT NOT NULL CHECK (feature = ANY (ARRAY[
                    'beneficiaries','push_notifications_monthly','cashiers',
                    'branches','collaborators','redeemable_products'
                  ])),
  limit_value     INTEGER NOT NULL CHECK (limit_value >= 0),
  warning_threshold NUMERIC(4,3) NOT NULL DEFAULT 0.800,
  snapshotted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, feature)
);

-- Enable RLS (matching other tables)
ALTER TABLE public.organization_plan_limits ENABLE ROW LEVEL SECURITY;

-- Index for fast lookups
CREATE INDEX idx_org_plan_limits_org_id ON public.organization_plan_limits(organization_id);

-- =============================================================
-- 2. Seed snapshot for ALL existing organizations
--    Each org gets limits from the plan_limits template based
--    on their current plan.
-- =============================================================
INSERT INTO public.organization_plan_limits (organization_id, plan, feature, limit_value, warning_threshold, snapshotted_at)
SELECT o.id, o.plan, pl.feature, pl.limit_value, pl.warning_threshold, COALESCE(o.trial_started_at, o.creation_date::timestamptz, now())
FROM public.organization o
JOIN public.plan_limits pl ON pl.plan = o.plan;

-- =============================================================
-- 3. Function to snapshot limits for an org from the template
--    Called when an org is created or changes plan.
-- =============================================================
CREATE OR REPLACE FUNCTION public.snapshot_plan_limits_for_org(p_org_id BIGINT, p_plan TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  -- Upsert: replace all feature limits for this org with the current template values
  INSERT INTO public.organization_plan_limits (organization_id, plan, feature, limit_value, warning_threshold, snapshotted_at)
  SELECT p_org_id, p_plan, pl.feature, pl.limit_value, pl.warning_threshold, now()
  FROM public.plan_limits pl
  WHERE pl.plan = p_plan
  ON CONFLICT (organization_id, feature)
  DO UPDATE SET
    plan              = EXCLUDED.plan,
    limit_value       = EXCLUDED.limit_value,
    warning_threshold = EXCLUDED.warning_threshold,
    snapshotted_at    = EXCLUDED.snapshotted_at,
    updated_at        = now();
END;
$function$;

-- =============================================================
-- 4. Trigger: on plan change, snapshot the NEW plan's limits
-- =============================================================
CREATE OR REPLACE FUNCTION public.snapshot_limits_on_plan_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  IF OLD.plan IS DISTINCT FROM NEW.plan THEN
    PERFORM public.snapshot_plan_limits_for_org(NEW.id, NEW.plan);
  END IF;
  RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_snapshot_limits_on_plan_change
  AFTER UPDATE OF plan ON public.organization
  FOR EACH ROW
  EXECUTE FUNCTION public.snapshot_limits_on_plan_change();

-- Also snapshot on org INSERT (new organizations)
CREATE OR REPLACE FUNCTION public.snapshot_limits_on_org_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  PERFORM public.snapshot_plan_limits_for_org(NEW.id, NEW.plan);
  RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_snapshot_limits_on_org_insert
  AFTER INSERT ON public.organization
  FOR EACH ROW
  EXECUTE FUNCTION public.snapshot_limits_on_org_insert();

-- =============================================================
-- 5. Update check_plan_limit to read from snapshot table
-- =============================================================
CREATE OR REPLACE FUNCTION public.check_plan_limit(org_id BIGINT, feature_name TEXT)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_plan              TEXT;
  v_limit_value       INTEGER;
  v_warning_threshold NUMERIC(4,3);
  v_current_usage     BIGINT := 0;
  v_role_id           BIGINT;
BEGIN
  SELECT plan INTO v_plan FROM public.organization WHERE id = org_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('allowed', false, 'reason', 'Organization not found');
  END IF;

  -- Read from the org's snapshotted limits instead of global plan_limits
  SELECT opl.limit_value, opl.warning_threshold
    INTO v_limit_value, v_warning_threshold
    FROM public.organization_plan_limits opl
    WHERE opl.organization_id = org_id AND opl.feature = feature_name;

  IF NOT FOUND THEN
    -- Fallback: if no snapshot exists yet, use the global template
    SELECT pl.limit_value, pl.warning_threshold
      INTO v_limit_value, v_warning_threshold
      FROM public.plan_limits pl
      WHERE pl.plan = v_plan AND pl.feature = feature_name;

    IF NOT FOUND THEN
      RETURN jsonb_build_object('allowed', true, 'reason', 'Feature not limited on this plan');
    END IF;
  END IF;

  CASE feature_name
    WHEN 'beneficiaries' THEN
      SELECT COUNT(*) INTO v_current_usage
        FROM public.beneficiary_organization
        WHERE organization_id = org_id AND is_active = true;

    WHEN 'push_notifications_monthly' THEN
      v_current_usage := COALESCE((
        SELECT notifications_sent_this_month
        FROM public.organization_notification_limits
        WHERE organization_id = org_id
      ), 0);

    WHEN 'cashiers' THEN
      SELECT id INTO v_role_id FROM public.user_role WHERE name = 'cashier';
      SELECT COUNT(*) INTO v_current_usage
        FROM public.app_user
        WHERE organization_id = org_id AND role_id = v_role_id AND active = true;

    WHEN 'branches' THEN
      SELECT COUNT(*) INTO v_current_usage
        FROM public.branch
        WHERE organization_id = org_id AND active = true;

    WHEN 'collaborators' THEN
      SELECT id INTO v_role_id FROM public.user_role WHERE name = 'collaborator';
      SELECT COUNT(*) INTO v_current_usage
        FROM public.app_user
        WHERE organization_id = org_id AND role_id = v_role_id AND active = true;

    WHEN 'redeemable_products' THEN
      SELECT COUNT(*) INTO v_current_usage
        FROM public.product
        WHERE organization_id = org_id AND active = true;

    ELSE
      v_current_usage := 0;
  END CASE;

  RETURN jsonb_build_object(
    'allowed',          v_current_usage < v_limit_value,
    'current_usage',    v_current_usage,
    'limit_value',      v_limit_value,
    'usage_percentage', LEAST(100, ROUND(v_current_usage::NUMERIC / NULLIF(v_limit_value,0) * 100)),
    'should_warn',      v_current_usage::NUMERIC / NULLIF(v_limit_value,0) >= v_warning_threshold,
    'plan',             v_plan,
    'feature',          feature_name
  );
END;
$function$;

-- =============================================================
-- 6. Update get_organization_usage_summary to read from snapshot
-- =============================================================
CREATE OR REPLACE FUNCTION public.get_organization_usage_summary(org_id BIGINT)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_plan                  TEXT;
  v_beneficiaries         BIGINT  := 0;
  v_notifications_month   INTEGER := 0;
  v_cashier_role_id       BIGINT;
  v_collaborator_role_id  BIGINT;
  v_cashiers              BIGINT  := 0;
  v_branches              BIGINT  := 0;
  v_collaborators         BIGINT  := 0;
  v_products              BIGINT  := 0;
  result                  JSONB;
BEGIN
  SELECT plan INTO v_plan FROM public.organization WHERE id = org_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Organization not found');
  END IF;

  SELECT COUNT(*) INTO v_beneficiaries
    FROM public.beneficiary_organization
    WHERE organization_id = org_id AND is_active = true;

  v_notifications_month := COALESCE((
    SELECT notifications_sent_this_month
    FROM public.organization_notification_limits
    WHERE organization_id = org_id
  ), 0);

  SELECT id INTO v_cashier_role_id      FROM public.user_role WHERE name = 'cashier';
  SELECT id INTO v_collaborator_role_id FROM public.user_role WHERE name = 'collaborator';

  SELECT COUNT(*) INTO v_cashiers
    FROM public.app_user
    WHERE organization_id = org_id AND role_id = v_cashier_role_id AND active = true;

  SELECT COUNT(*) INTO v_branches
    FROM public.branch
    WHERE organization_id = org_id AND active = true;

  SELECT COUNT(*) INTO v_collaborators
    FROM public.app_user
    WHERE organization_id = org_id AND role_id = v_collaborator_role_id AND active = true;

  SELECT COUNT(*) INTO v_products
    FROM public.product
    WHERE organization_id = org_id AND active = true;

  -- Read from org's snapshotted limits, falling back to global template
  SELECT jsonb_build_object(
    'plan', v_plan,
    'features', jsonb_agg(
      jsonb_build_object(
        'feature',           limits.feature,
        'limit_value',       limits.limit_value,
        'warning_threshold', limits.warning_threshold,
        'current_usage', CASE limits.feature
          WHEN 'beneficiaries'              THEN v_beneficiaries
          WHEN 'push_notifications_monthly' THEN v_notifications_month
          WHEN 'cashiers'                   THEN v_cashiers
          WHEN 'branches'                   THEN v_branches
          WHEN 'collaborators'              THEN v_collaborators
          WHEN 'redeemable_products'        THEN v_products
          ELSE 0
        END,
        'is_at_limit', CASE limits.feature
          WHEN 'beneficiaries'              THEN v_beneficiaries       >= limits.limit_value
          WHEN 'push_notifications_monthly' THEN v_notifications_month >= limits.limit_value
          WHEN 'cashiers'                   THEN v_cashiers            >= limits.limit_value
          WHEN 'branches'                   THEN v_branches            >= limits.limit_value
          WHEN 'collaborators'              THEN v_collaborators       >= limits.limit_value
          WHEN 'redeemable_products'        THEN v_products            >= limits.limit_value
          ELSE false
        END,
        'should_warn', CASE limits.feature
          WHEN 'beneficiaries'              THEN v_beneficiaries::NUMERIC       / NULLIF(limits.limit_value,0) >= limits.warning_threshold
          WHEN 'push_notifications_monthly' THEN v_notifications_month::NUMERIC / NULLIF(limits.limit_value,0) >= limits.warning_threshold
          WHEN 'cashiers'                   THEN v_cashiers::NUMERIC            / NULLIF(limits.limit_value,0) >= limits.warning_threshold
          WHEN 'branches'                   THEN v_branches::NUMERIC            / NULLIF(limits.limit_value,0) >= limits.warning_threshold
          WHEN 'collaborators'              THEN v_collaborators::NUMERIC       / NULLIF(limits.limit_value,0) >= limits.warning_threshold
          WHEN 'redeemable_products'        THEN v_products::NUMERIC            / NULLIF(limits.limit_value,0) >= limits.warning_threshold
          ELSE false
        END,
        'usage_percentage', LEAST(100, ROUND(
          CASE limits.feature
            WHEN 'beneficiaries'              THEN v_beneficiaries::NUMERIC       / NULLIF(limits.limit_value,0) * 100
            WHEN 'push_notifications_monthly' THEN v_notifications_month::NUMERIC / NULLIF(limits.limit_value,0) * 100
            WHEN 'cashiers'                   THEN v_cashiers::NUMERIC            / NULLIF(limits.limit_value,0) * 100
            WHEN 'branches'                   THEN v_branches::NUMERIC            / NULLIF(limits.limit_value,0) * 100
            WHEN 'collaborators'              THEN v_collaborators::NUMERIC       / NULLIF(limits.limit_value,0) * 100
            WHEN 'redeemable_products'        THEN v_products::NUMERIC            / NULLIF(limits.limit_value,0) * 100
            ELSE 0
          END
        ))
      )
      ORDER BY limits.feature
    )
  ) INTO result
  FROM (
    -- Prefer org snapshot; fall back to global template
    SELECT COALESCE(opl.feature, pl.feature) AS feature,
           COALESCE(opl.limit_value, pl.limit_value) AS limit_value,
           COALESCE(opl.warning_threshold, pl.warning_threshold) AS warning_threshold
    FROM public.plan_limits pl
    LEFT JOIN public.organization_plan_limits opl
      ON opl.organization_id = org_id AND opl.feature = pl.feature
    WHERE pl.plan = v_plan
  ) limits;

  RETURN result;
END;
$function$;
